import Foundation

/// A unique identifier for an ACP session.
///
/// Session IDs are opaque strings that uniquely identify a conversation
/// between a client and agent. They are generated by the agent when a
/// session is created and used in all subsequent session-scoped operations.
public struct SessionId: Hashable, Codable, Sendable {
    public let value: String

    /// Creates a new session ID with a random UUID.
    public init() {
        self.value = UUID().uuidString
    }

    /// Creates a session ID from an existing string value.
    ///
    /// - Parameter value: The session ID string
    public init(value: String) {
        self.value = value
    }

    // MARK: - Codable

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.value = try container.decode(String.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}

// MARK: - CustomStringConvertible

extension SessionId: CustomStringConvertible {
    public var description: String {
        value
    }
}

// MARK: - ExpressibleByStringLiteral

extension SessionId: ExpressibleByStringLiteral {
    public init(stringLiteral value: String) {
        self.value = value
    }
}
