# SwiftLint Configuration for ACP Swift SDK

# Opt-in rules - keep minimal set for cleaner code
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - closure_spacing
  - operator_usage_whitespace

# Disabled rules
disabled_rules:
  - todo
  - line_length
  - redundant_string_enum_value
  - explicit_top_level_acl
  - explicit_enum_raw_value
  - modifier_order
  - multiline_parameters
  - redundant_type_annotation
  - nesting
  - identifier_name
  - for_where
  - unused_closure_parameter
  - file_length
  - type_body_length

# File length limits
file_length:
  warning: 1000
  error: 3000
  ignore_comment_only_lines: true

# Type body length limits
type_body_length:
  warning: 800
  error: 2000

# Function body length limits
function_body_length:
  warning: 60
  error: 150

# Cyclomatic complexity - relaxed
cyclomatic_complexity:
  warning: 15
  error: 25

# Function parameter count - relaxed
function_parameter_count:
  warning: 6
  error: 10

# Type name rules
type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL
    - URI

# Excluded paths
excluded:
  - .build
  - .swiftpm
  - Tests/LinuxMain.swift
  - Samples

# Reporter
reporter: "xcode"
